package.json, packages/strapi/package.json, packages/strapi/src/generators/init/generator.spec.ts, packages/strapi/src/generators/init/init.impl.ts, yarn.lock
Changed the dependency to the new cli and updated the corresponding import.
Not sure if this was the case before but running the generator through Nx Console will not work properly.
Strapi files will be created during the dry-run but config files like workspace.json are not updated. The subsequent (non-dry) run will then fail because the directory already exists.
`nx g @nx-extend/strapi:init` works fine.
closes #32
closes #38
=> fix(strapi): update to strapi v4

packages/strapi/src/executors/serve/schema.json, packages/strapi/src/executors/serve/serve.impl.ts
The `strapi` package has an executor `serve`
The executor is passing through whitelisted arguments from the nx-command.
- --no-build
- --watch-admin
- --browser
Currently possible arguments documented here:  
https://docs.strapi.io/developer-docs/latest/developer-resources/cli/CLI.html#strapi-develop
=> feat: add arguments to the strapi serve command

packages/gcp-functions/src/generators/init/files-http/package.json.template, packages/gcp-functions/src/generators/init/files-http/src/main.ts.template, packages/gcp-functions/src/generators/init/init.impl.ts
👋🏻  Hello ^_^
I have been a big fan of Nx for a while and recently had the need to create some Cloud Functions in GCP. After looking at the community plugins, I decided to go with yours as there are other GCP related plugins in your repo should I need them. I had a few issues creating a new project though so, instead of just fixing them for myself, I decided to share the wealth ^_^
Changes:
- `init.impl.ts`: This was my main issue when creating the project. When a project is created, it doesn't add the `@google-cloud/functions-framework` package to the workspace but it's referenced in `main.ts`. Adding this change fixes that issue.
- `main.ts.template`: This was related to the above.  `HttpFunction` is exported at the package's top level so diving deeper isn't needed and, depending on the …
=> chore(gcp-functions): project init fixes and cleanup

packages/terraform/src/utils/create-executor.ts
Command signature is `terraform apply [options] [plan file]`.  
Currently `@nx-extend/terraform:apply` executes as `terraform apply defaultplan -auto-approve` which gives  
`Error: Too many command line arguments. Expected at most one positional argument.`
=> fix(terraform): Fixed apply autoApproval

packages/pulumi/src/executors/up/up.impl.ts
Fixes #142.
Marked as draft, as I am not sure how to test it. If you think it's okay to merge without testing, let me know.
=> feat(pulumi): Support `--yes` and `--skipPreview` options

packages/pulumi/src/generators/init/files/index.ts.template
fixes #157
ESLint will make the import of `pulumi` go to the top, which makes it run before the tsconfig-paths import.
=> fix: eslint breaking import order

packages/pulumi/src/generators/init/files/index.ts.template
Today, when working with [Pulumi Stack References](https://www.pulumi.com/learn/building-with-pulumi/stack-references/), they are not strong-typed.
With this project, we have the potential to make them strong-typed by emitting just a small helper method that does just that.
I think the end-result is really cool.
So now, when referencing other stacks, their outputs and return types etc are strong-typed.
=> feat: add helper for strong-typed stack references

packages/pulumi/executors.json
May fix #166.
Unsure why the executors are both in the "builders" and "executors" section though? Aren't they just executors? I guess builders is something else, right?
If that's the case, we should remove the builders section.
=> fix: update executors

packages/strapi/src/with-nx.ts
This will also make it work when extending the project graph
=> fix(strapi): Use cached project graph for `withNx`

packages/terraform/src/executors/providers/schema.json, packages/terraform/src/generators/init/init.impl.ts, packages/terraform/src/utils/create-executor.ts
Enhanced the providers executor to be able to pass the lock option.
=> feat: Added lock option to providers target.

packages/e2e-runner/README.md, packages/e2e-runner/src/executors/run/utils/nx-target.ts
Use the new `logging` option on a target to either enable, or disable the logging output for the specified target.
Closes #202
I tried adding some component tests; but I can't seem to mock `child_process.spawn` properly without adding extra libraries.
=> feat(e2e-runner): enable or disable target logging via options

packages/pulumi/src/executors/preview/preview.impl.ts, packages/pulumi/src/executors/refresh/refresh.impl.ts, packages/pulumi/src/executors/up/up.impl.ts
This is a new feature I helped introduce in Pulumi: https://github.com/pulumi/pulumi/releases/tag/v3.105.0
It doesn't emit a gazillion dots to the standard out.
=> feat: don't emit dots in CLI output

packages/terraform/src/executors/validate/schema.json, packages/terraform/src/utils/create-executor.ts
Fix schema typo.
Validate command needs `''` added otherwise the command ends up being `terraform validate true`
=> fix(terraform): fix terraform validate executor schema and command

packages/gcp-functions/src/executors/build/build.impl.ts, packages/gcp-functions/src/executors/build/schema.json, packages/gcp-functions/src/utils/generate-package-json.ts
Fixes #250 
Adds an option called `omitOptionalDependencies`. This will control the `isProduction` flag in `@nx/js`'s `createPackageJson` function.
=> feat(gcp-functions): allow keeping optional peerDeps and devDeps

packages/core/package.json
In the company I work for, we must respect all Open Source licenses. And since this is unlicensed, we can't use it anymore unless we provide the license here.
=> fix: add license

packages/pulumi/src/executors/preview/schema.json, packages/pulumi/src/executors/refresh/schema.json, packages/pulumi/src/executors/up/schema.json
Due to recent changes in NX, non-existent options are no longer passed down to the executor.
I found that the "stack" option at least isn't anymore. I suspect it's because it doesn't exist in the schema.
=> fix: add missing stack property

packages/firebase-hosting/src/executors/deploy/deploy.impl.ts, packages/shadcn-ui/migrations.json, packages/shadcn-ui/src/generators/init/init.impl.ts, packages/shadcn-ui/src/migrations/change-add-executor/change-add-executor.spec.ts, packages/shadcn-ui/src/migrations/change-add-executor/change-add-executor.ts
=> fix(shadcn-ui): Rename `add` executor to `add-component`

packages/gcp-cloud-run/package.json, packages/gcp-cloud-run/src/utils/get-valid-secrets.ts, packages/gcp-functions/package.json, packages/gcp-functions/src/utils/get-valid-secrets.ts
When running a command like the one below, the secrets are parsed as if they're an array/object. This should resolve that
```bash
nx deploy "some-function" ... "--secrets" "[ENV_FILE=some-env]"
```
=> Add fix to support passing in JSON as string via command line arguments

packages/terraform/src/utils/create-executor.ts
Terraform CLi expects a "--var" argument to be passed when a variable is defined dynamically with no default value. The new variable serves the same purpose of "varFile" but expects a string value rather than a file path
=> Added varString as CLi argument

packages/terraform/src/utils/create-executor.ts
- Parse backendConfig if its type is string
- Added "reconfigure" parameter for the "init" command
=> - Added type check for backendConfig

packages/vercel/src/executors/deploy/deploy.impl.ts, packages/vercel/src/executors/deploy/schema.json
This option can be passed to the executor options to make the Vercel CLI archive the build before uploading.
This is required for projects with >15000 files, as the Vercel CLI will otherwise throw an error: 
```
Error: Invalid request: `files` should NOT have more than 15000 items, received 17185.
```
Thanks for creating this and please let me know if you'd like me to add anything else to the PR 😄
=> feat(vercel): add archive option for deploy executor

packages/vercel/src/executors/deploy/schema.json
Just cleaning the default value that was left there by mistake 😄
=> fix(vercel): remove  archive option for deploy executor

packages/terraform/src/graph.ts
The path resolution for deeply nested modules has a bug where it doesn't resolve the correct absolute path.
=> bug(terraform): Fix path resolution for nested modules

packages/shadcn-ui/src/executors/add/add.impl.ts
The latest version of the UI package does not include the CLI anymore, it's published under `shadcn` now - this PR fixes that by pinning the version to `0.8.0`, the latest previous version that works.
It would be nice to start using the new CLI, but it's incompatible with the current setup inside NX: it expects package.json and components.json to be defined within the same directory. I think the better approach would be to implement a NX-specific version of the `add` command instead of using the upstream CLI - it's [not particularly complex](https://github.com/shadcn-ui/ui/blob/main/packages/cli/src/commands/add.ts).
=> Pin version of shadcn, fixes #309

packages/gcp-functions/src/executors/deploy/deploy.impl.ts, packages/gcp-functions/src/executors/deploy/schema.json, packages/gcp-functions/src/index.ts, packages/gcp-functions/src/types/index.ts, packages/gcp-functions/src/utils/validate-resources.spec.ts, packages/gcp-functions/src/utils/validate-resources.ts
- Allows 8 GB memory for Gen 1 functions
- Allows 16 GB and 32GB for Gen 2 functions
- Adds validation logic to ensure that CPU allocations are consistent with memory limits
=> Extend allowed memory for GCP functions

e2e/shadcn-ui-e2e/tests/shadcn-ui.spec.ts, packages/shadcn-ui/src/executors/add/add.impl.ts, packages/shadcn-ui/src/generators/init/init.impl.ts
Fix #309 #340
Move `shadcn-ui` CLI to `shadcn` CLI for add components.
=> feat(shadcn-ui): move shadcn-ui to shadcn

packages/docusaurus/package.json, yarn.lock
In 4.0.0 Nx was upgraded to 21 but the peer dependency for @nx/devkit was still set to 20. This updates the peer dependency ^21.0.0.
=> chore(docusaurus): bump @nx/devkit to ^21.0.0

packages/docusaurus/package.json
As per [@docusaurus/core package.json](https://github.com/facebook/docusaurus/blob/main/packages/docusaurus/package.json) and the [release notes](https://github.com/facebook/docusaurus/releases/tag/v3.7.0) docusaurus supports react 19 since 3.7.0. This would enable nx-extend/docusaurus to be installed in codebases that use React-router 7, and other codebases that use react 19.
=> Update peerDeps to allow react 19
